In [3]:
!python.exe -m pip install --upgrade pip


  Using cached pip-25.1.1-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-25.1.1-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 25.0.1
    Uninstalling pip-25.0.1:
      Successfully uninstalled pip-25.0.1


In [4]:
! pip install numpy


In [5]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
print(arr.shape)
print(arr.dtype)
print(type(arr))


(10,)
int64
<class 'numpy.ndarray'>


In [12]:
matrix = np.array([[1,2,3],[4,5,6]])
print (matrix)
print(matrix.shape)
print(matrix.dtype)
print(matrix.ndim)


[[1 2 3]
 [4 5 6]]
(2, 3)
int64
2


In [15]:
print(np.eye(4))
print(np.full((3,4),0))
print(np.zeros((2,3)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
print(np.random.rand(2,3))
print(np.random.randn(2,3))

[[0.37419977 0.85767244 0.62731707]
 [0.05463415 0.61181788 0.59776762]]
[[-0.30657556 -0.81854     0.2098917 ]
 [ 0.88373525  1.27044426  0.19121926]]


In [21]:
print(arr[0])
print(arr[-1])
print(arr[1:3])
print(arr[:3])
print(arr[3:])


1
10
[2 3]
[1 2 3]
[ 4  5  6  7  8  9 10]
